/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.police;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Wrapper;
import javax.swing.JOptionPane;

/**
 *
 * @author Isaack
 */
public class Admin extends javax.swing.JFrame {
    static final String DB_URL = "jdbc:mysql://localhost/police_management_system";
 
	    //  Database credentials
	    static final String USER = "root" ;
	    static final String PASS = "Isaamille2017";
            protected static final String String = null;

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogin = new javax.swing.JPanel();
        lblAdmin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFieldUsername = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jlblPassword = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setSize(new java.awt.Dimension(775, 497));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLogin.setBackground(new java.awt.Color(30, 40, 55));
        jPanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdmin.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lblAdmin.setText("ADMIN");
        jPanelLogin.add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, 30));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USERNAME");
        jPanelLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 110, 30));

        txtFieldUsername.setBackground(new java.awt.Color(30, 40, 55));
        txtFieldUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFieldUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtFieldUsername.setText("Enter your username");
        txtFieldUsername.setBorder(null);
        txtFieldUsername.setName("username"); // NOI18N
        txtFieldUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldUsernameFocusGained(evt);
            }
        });
        txtFieldUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFieldUsernameMouseClicked(evt);
            }
        });
        txtFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldUsernameActionPerformed(evt);
            }
        });
        jPanelLogin.add(txtFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 280, 30));
        jPanelLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 280, 10));
        jPanelLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 280, -1));

        jlblPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jlblPassword.setForeground(new java.awt.Color(255, 255, 255));
        jlblPassword.setText("PASSWORD");
        jPanelLogin.add(jlblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 100, 30));

        password.setBackground(new java.awt.Color(30, 40, 55));
        password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password.setText("Enter your password");
        password.setBorder(null);
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        jPanelLogin.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 280, 30));

        btnLogin.setBackground(new java.awt.Color(0, 204, 204));
        btnLogin.setText("SIGN IN");
        btnLogin.setBorder(null);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanelLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 373, 120, 50));

        getContentPane().add(jPanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 500, 600));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/admin1.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 160, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldUsernameActionPerformed

    private void txtFieldUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldUsernameMouseClicked
        txtFieldUsername.setText(" ");
    }//GEN-LAST:event_txtFieldUsernameMouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        // TODO add your handling code here:
        password.setText("");
    }//GEN-LAST:event_passwordMouseClicked

    private void txtFieldUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldUsernameFocusGained
        // TODO add your handling code here:
        txtFieldUsername.setText("");
    }//GEN-LAST:event_txtFieldUsernameFocusGained

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        Wrapper conn = null;
        if (txtFieldUsername.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please Enter your Badge Number");
        }else if(password.getPassword().length==0){
            JOptionPane.showMessageDialog(null, "Enter a valid password");
        }else{
            String user = txtFieldUsername.getText();   // Collecting the input
            char[] pass = password.getPassword(); // Collecting the input
            String pwd = String.copyValueOf(pass);  // converting from array to string
            if (validate_login(user, pwd)) {
                JOptionPane.showMessageDialog(null, "Correct Login Credentials");
                
                AdminHome home = new AdminHome();
                home.setSize(1200,650);
                home.setLocationRelativeTo(null);
                home.pack();
                home.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Incorrect Login Credentials");
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private boolean validate_login(String username,String password) {
        try{           
       Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
       Connection conn = DriverManager.getConnection(DB_URL,USER,PASS);
       System.out.println("Connected database successfully...");
       PreparedStatement pst = (PreparedStatement) conn.prepareStatement("Select username,password"
               + " from admin where username=? and password=?");
       pst.setString(1, username); 
       pst.setString(2, password);
       ResultSet rs = pst.executeQuery();                        
       if(rs.next())            
           return true;    
       else
           return false;            
   }
   catch(Exception e){
       e.printStackTrace();
       return false;
   }       
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlblPassword;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField txtFieldUsername;
    // End of variables declaration//GEN-END:variables
}
