/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.police;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Isaack
 */
public class CaseOverview extends javax.swing.JFrame {
        static final String DB_URL = "jdbc:mysql://localhost/police_management_system";
        //  Database credentials
        static final String USER = "root" ;
        static final String PASS = "Isaamille2017";

    /**
     * Creates new form CaseOverview
     */
    public CaseOverview() {
        initComponents();
        Show_Cases_In_Table();
    }
    
    public Connection getConnection(){
        Connection conn;
        try {
            conn = DriverManager.getConnection(DB_URL, USER, PASS); 
            return conn;
        } catch (SQLException e) {
            return null;
        }
    }
    
     public ArrayList<Case> getCaseList(){
        ArrayList<Case> caseList;
        caseList = new ArrayList<>();
        Connection connection = getConnection();
        
        String query = "SELECT * FROM cases";
        Statement st;
        ResultSet rs;
        
        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Case cases;
            while (rs.next()) {                
                cases = new Case(rs.getInt("case_id"),
                rs.getString("case_name"),rs.getString("case_type"));
                caseList.add(cases);
            }
        } catch (SQLException e) {
        }
        return caseList;
    }
    
//    DISPLAY DATA IN THE JTABLE
    public final void Show_Cases_In_Table(){
        ArrayList<Case> list;
        list = getCaseList();
        DefaultTableModel model = (DefaultTableModel) jTable_Display_Cases.getModel();
        Object[] row = new Object[3];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getCaseID();
            row[1] = list.get(i).getCaseName();
            row[2] = list.get(i).getCaseType();
            model.addRow(row);
        }
    }
    
    public void excecuteSQLQuery(String query, String message){
        Connection con = getConnection();
        Statement st;
        try {
            st = con.createStatement();
            if ((st.executeUpdate(query) == 1)) {
                //Refresh the Data in the table
                DefaultTableModel model = (DefaultTableModel) jTable_Display_Cases.getModel();
                model.setRowCount(0);
                Show_Cases_In_Table();
                JOptionPane.showMessageDialog(null, "Data "+message+" Succesfully");
            }else{
               JOptionPane.showMessageDialog(null, "Data Not "+message);
            }
        } catch (Exception e) {
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelLogin = new javax.swing.JPanel();
        lblCases = new javax.swing.JLabel();
        lblCasename = new javax.swing.JLabel();
        txtCasename = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblCasetype = new javax.swing.JLabel();
        cbCasetype = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_Cases = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblCasename1 = new javax.swing.JLabel();
        txtCaseID = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblExit = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLogin.setBackground(new java.awt.Color(30, 40, 55));
        jPanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCases.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblCases.setForeground(new java.awt.Color(255, 255, 255));
        lblCases.setText("CASES OVERVIEW");
        jPanelLogin.add(lblCases, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 170, 30));

        lblCasename.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblCasename.setForeground(new java.awt.Color(255, 255, 255));
        lblCasename.setText("CASE NAME");
        jPanelLogin.add(lblCasename, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 190, 30));

        txtCasename.setBackground(new java.awt.Color(30, 40, 55));
        txtCasename.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCasename.setForeground(new java.awt.Color(255, 255, 255));
        txtCasename.setText("Enter the case name");
        txtCasename.setBorder(null);
        txtCasename.setName("username"); // NOI18N
        txtCasename.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCasenameFocusGained(evt);
            }
        });
        txtCasename.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCasenameMouseClicked(evt);
            }
        });
        txtCasename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCasenameActionPerformed(evt);
            }
        });
        jPanelLogin.add(txtCasename, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 280, 30));
        jPanelLogin.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 280, 10));

        lblCasetype.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblCasetype.setForeground(new java.awt.Color(255, 255, 255));
        lblCasetype.setText("CASE TYPE");
        jPanelLogin.add(lblCasetype, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 110, 30));

        cbCasetype.setBackground(new java.awt.Color(30, 40, 55));
        cbCasetype.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cbCasetype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rape", "Robbery with Violence", "Carjacking", "Robbery", "Pickpocketing", " " }));
        jPanelLogin.add(cbCasetype, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 280, 30));
        jPanelLogin.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 280, 10));

        jTable_Display_Cases.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTable_Display_Cases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Case ID", "Case Name", "Case Type"
            }
        ));
        jTable_Display_Cases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Display_CasesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Display_Cases);

        jPanelLogin.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 810, 400));

        btnDelete.setBackground(new java.awt.Color(0, 204, 204));
        btnDelete.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/delete.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.setBorder(null);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanelLogin.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 150, 60));

        btnUpdate.setBackground(new java.awt.Color(0, 204, 204));
        btnUpdate.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/update.png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.setBorder(null);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanelLogin.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 150, 60));

        lblCasename1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblCasename1.setForeground(new java.awt.Color(255, 255, 255));
        lblCasename1.setText("CASE ID");
        jPanelLogin.add(lblCasename1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 190, 30));

        txtCaseID.setBackground(new java.awt.Color(30, 40, 55));
        txtCaseID.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCaseID.setForeground(new java.awt.Color(255, 255, 255));
        txtCaseID.setText("Enter the case ID");
        txtCaseID.setBorder(null);
        txtCaseID.setName("username"); // NOI18N
        txtCaseID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCaseIDFocusGained(evt);
            }
        });
        txtCaseID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCaseIDMouseClicked(evt);
            }
        });
        txtCaseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaseIDActionPerformed(evt);
            }
        });
        jPanelLogin.add(txtCaseID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, 30));
        jPanelLogin.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 280, 10));

        lblExit.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/exit2.png"))); // NOI18N
        lblExit.setText("EXIT");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        jPanelLogin.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, 70, 40));

        lblBack.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblBack.setForeground(new java.awt.Color(255, 255, 255));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/back4.png"))); // NOI18N
        lblBack.setText("BACK");
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        jPanelLogin.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 40));

        jPanel1.add(jPanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 650));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCasenameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCasenameFocusGained
        // TODO add your handling code here:
        txtCasename.setText("");
    }//GEN-LAST:event_txtCasenameFocusGained

    private void txtCasenameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCasenameMouseClicked
        // TODO add your handling code here:
        txtCasename.setText("");
    }//GEN-LAST:event_txtCasenameMouseClicked

    private void txtCasenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCasenameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCasenameActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String query = "DELETE FROM cases where case_id='"+txtCaseID.getText()+"'";
        excecuteSQLQuery(query, "Deleted");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         String query = "UPDATE cases SET case_name='"+txtCasename.getText()+"', "
                + "case_type='"+cbCasetype.getSelectedItem().toString()+"' "
                 + "WHERE case_id='"+txtCaseID.getText()+"'";
            excecuteSQLQuery(query, "Updated");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jTable_Display_CasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_CasesMouseClicked
        // TODO add your handling code here:
        //Display Selected Row in JTextFields
        int i = jTable_Display_Cases.getSelectedRow();
        TableModel model = jTable_Display_Cases.getModel();
        txtCaseID.setText(model.getValueAt(i, 0).toString());
        txtCasename.setText(model.getValueAt(i, 1).toString());
        cbCasetype.setSelectedItem(model.getValueAt(i, 2).toString());
       
    }//GEN-LAST:event_jTable_Display_CasesMouseClicked

    private void txtCaseIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCaseIDFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaseIDFocusGained

    private void txtCaseIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCaseIDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaseIDMouseClicked

    private void txtCaseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaseIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaseIDActionPerformed

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        // TODO add your handling code here:
        AdminHome admin = new AdminHome();
        admin.setSize(1200,650);
        admin.setLocationRelativeTo(null);
        admin.pack();
        admin.setVisible(true);
    }//GEN-LAST:event_lblBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaseOverview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaseOverview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaseOverview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaseOverview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaseOverview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbCasetype;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable_Display_Cases;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblCasename;
    private javax.swing.JLabel lblCasename1;
    private javax.swing.JLabel lblCases;
    private javax.swing.JLabel lblCasetype;
    private javax.swing.JLabel lblExit;
    private javax.swing.JTextField txtCaseID;
    private javax.swing.JTextField txtCasename;
    // End of variables declaration//GEN-END:variables
}
