/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.police;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Isaack
 */
public class Cases extends javax.swing.JFrame {
      static final String DB_URL = "jdbc:mysql://localhost/police_management_system";
 
        //  Database credentials
        static final String USER = "root" ;
        static final String PASS = "Isaamille2017";
    /**
     * Creates new form cases
     */
    public Cases() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCases = new javax.swing.JPanel();
        lblCasetype = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtCasename = new javax.swing.JTextField();
        lblCases = new javax.swing.JLabel();
        lblCasename = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        lblBack = new javax.swing.JLabel();
        cbCasetype = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCases.setBackground(new java.awt.Color(30, 40, 55));
        jPanelCases.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCasetype.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblCasetype.setForeground(new java.awt.Color(255, 255, 255));
        lblCasetype.setText("CASE TYPE");
        jPanelCases.add(lblCasetype, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 110, 30));
        jPanelCases.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 280, 10));
        jPanelCases.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 280, 10));

        txtCasename.setBackground(new java.awt.Color(30, 40, 55));
        txtCasename.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCasename.setForeground(new java.awt.Color(255, 255, 255));
        txtCasename.setText("Enter the case name");
        txtCasename.setBorder(null);
        txtCasename.setName("username"); // NOI18N
        txtCasename.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCasenameFocusGained(evt);
            }
        });
        txtCasename.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCasenameMouseClicked(evt);
            }
        });
        txtCasename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCasenameActionPerformed(evt);
            }
        });
        jPanelCases.add(txtCasename, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 280, 30));

        lblCases.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblCases.setForeground(new java.awt.Color(255, 255, 255));
        lblCases.setText("CASES");
        jPanelCases.add(lblCases, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 110, 30));

        lblCasename.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblCasename.setForeground(new java.awt.Color(255, 255, 255));
        lblCasename.setText("CASE NAME");
        jPanelCases.add(lblCasename, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 190, 30));

        btnSubmit.setBackground(new java.awt.Color(0, 255, 204));
        btnSubmit.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanelCases.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 100, 40));

        lblBack.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblBack.setForeground(new java.awt.Color(255, 255, 255));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/back4.png"))); // NOI18N
        lblBack.setText("BACK");
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        jPanelCases.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 40));

        cbCasetype.setBackground(new java.awt.Color(30, 40, 55));
        cbCasetype.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cbCasetype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rape", "Robbery with Violence", "Carjacking", "Robbery", "Pickpocketing", " " }));
        jPanelCases.add(cbCasetype, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 280, 30));

        getContentPane().add(jPanelCases, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCasenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCasenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCasenameActionPerformed

    private void txtCasenameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCasenameMouseClicked
        // TODO add your handling code here:
        txtCasename.setText("");
    }//GEN-LAST:event_txtCasenameMouseClicked

    private void txtCasenameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCasenameFocusGained
        // TODO add your handling code here:
         txtCasename.setText("");
    }//GEN-LAST:event_txtCasenameFocusGained

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if (txtCasename.getText().length()==0) {
            JOptionPane.showMessageDialog(null, "Please enter a valid Case Name");
            txtCasename.setText("");
        }else if(cbCasetype.getItemCount()==0){
            JOptionPane.showMessageDialog(null, "Please choose a  Valid Case Type");
        }

        String caseName = txtCasename.getText();
        String caseType = (String) cbCasetype.getSelectedItem();
        

        if (isInt(caseName)) {
            JOptionPane.showMessageDialog(null, "Please Enter a Valid Case ID");
            txtCasename.setText("");
        }else{
            try {

                Class.forName("com.mysql.jdbc.Driver");
                System.out.println("Connecting to a selected database...");
                //STEP 3: Open a connection
                Connection conn = DriverManager.getConnection(DB_URL,USER,PASS);
                System.out.println("Connected database successfully...");
               
                PreparedStatement statement = conn.prepareStatement("INSERT INTO "
                    + "cases (case_name,case_type)VALUES('"+txtCasename.getText()+"',"
                    + "'"+cbCasetype.getSelectedItem()+"')");
                statement.execute();
                System.out.println("Query Excecuted Succesfully");
                JOptionPane.showMessageDialog(null, "Insertion Succesful");
                PoliceHome police = new PoliceHome();
                police.setSize(775,497);
                police.setLocationRelativeTo(null);
                police.pack();
                police.setVisible(true);

            }catch (ClassNotFoundException | SQLException a) //catch block
            {
                a.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    public static boolean isInt(String s){
        for (int i = 0; i < s.length(); i++) {
            if (!Character.isDigit(s.charAt(i))) {
                return false;
            }
        }
        return true;
    }
    
    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        // TODO add your handling code here:
        Police police = new Police();
        police.setSize(775,497);
        police.setLocationRelativeTo(null);
        police.pack();
        police.setVisible(true);
    }//GEN-LAST:event_lblBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cases().setSize(775,497);
                new Cases().setLocationRelativeTo(null);
                new Cases().pack();
                new Cases().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbCasetype;
    private javax.swing.JPanel jPanelCases;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblCasename;
    private javax.swing.JLabel lblCases;
    private javax.swing.JLabel lblCasetype;
    private javax.swing.JTextField txtCasename;
    // End of variables declaration//GEN-END:variables
}
