/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.police;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Isaack
 */
public class Complainant extends javax.swing.JFrame {
        static final String DB_URL = "jdbc:mysql://localhost/police_management_system";
 
        //  Database credentials
        static final String USER = "root" ;
        static final String PASS = "Isaamille2017";

    /**
     * Creates new form Complainant
     */
    public Complainant() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelComplainant = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtFirstname = new javax.swing.JTextField();
        lblFirstname = new javax.swing.JLabel();
        txtCaseID = new javax.swing.JTextField();
        lblCaseid = new javax.swing.JLabel();
        lblCases = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtNationalid = new javax.swing.JTextField();
        lblNationalid = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtLastName = new javax.swing.JTextField();
        lblLastname = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        lblBack = new javax.swing.JLabel();
        jComboBoxCaseID = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelComplainant.setBackground(new java.awt.Color(30, 40, 55));
        jPanelComplainant.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelComplainant.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 280, 10));
        jPanelComplainant.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 280, 10));

        txtFirstname.setBackground(new java.awt.Color(30, 40, 55));
        txtFirstname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtFirstname.setForeground(new java.awt.Color(255, 255, 255));
        txtFirstname.setText("Enter the complainant first name");
        txtFirstname.setBorder(null);
        txtFirstname.setName("username"); // NOI18N
        txtFirstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFirstnameFocusGained(evt);
            }
        });
        txtFirstname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFirstnameMouseClicked(evt);
            }
        });
        txtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstnameActionPerformed(evt);
            }
        });
        jPanelComplainant.add(txtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 280, 30));

        lblFirstname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblFirstname.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstname.setText("COMPLAINANT FIRST NAME");
        jPanelComplainant.add(lblFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 240, 30));

        txtCaseID.setBackground(new java.awt.Color(30, 40, 55));
        txtCaseID.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCaseID.setForeground(new java.awt.Color(255, 255, 255));
        txtCaseID.setText("Enter the case ID");
        txtCaseID.setBorder(null);
        txtCaseID.setName("username"); // NOI18N
        txtCaseID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCaseIDFocusGained(evt);
            }
        });
        txtCaseID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCaseIDMouseClicked(evt);
            }
        });
        txtCaseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaseIDActionPerformed(evt);
            }
        });
        txtCaseID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCaseIDKeyReleased(evt);
            }
        });
        jPanelComplainant.add(txtCaseID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 280, 30));

        lblCaseid.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCaseid.setForeground(new java.awt.Color(255, 255, 255));
        lblCaseid.setText("CASE ID");
        jPanelComplainant.add(lblCaseid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 110, 30));

        lblCases.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        lblCases.setForeground(new java.awt.Color(255, 255, 255));
        lblCases.setText("COMPLAINANT");
        jPanelComplainant.add(lblCases, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 180, 30));

        lblPhone.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblPhone.setText("COMPLAINANT PHONE");
        jPanelComplainant.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 240, 30));

        txtPhone.setBackground(new java.awt.Color(30, 40, 55));
        txtPhone.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(255, 255, 255));
        txtPhone.setText("Enter the complainant phone number");
        txtPhone.setBorder(null);
        txtPhone.setName("username"); // NOI18N
        txtPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPhoneFocusGained(evt);
            }
        });
        txtPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPhoneMouseClicked(evt);
            }
        });
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        jPanelComplainant.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 280, 30));
        jPanelComplainant.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 280, 10));
        jPanelComplainant.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 280, 10));

        txtNationalid.setBackground(new java.awt.Color(30, 40, 55));
        txtNationalid.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNationalid.setForeground(new java.awt.Color(255, 255, 255));
        txtNationalid.setText("Enter the complainant national ID");
        txtNationalid.setBorder(null);
        txtNationalid.setName("username"); // NOI18N
        txtNationalid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNationalidFocusGained(evt);
            }
        });
        txtNationalid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNationalidMouseClicked(evt);
            }
        });
        txtNationalid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNationalidActionPerformed(evt);
            }
        });
        jPanelComplainant.add(txtNationalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 280, 30));

        lblNationalid.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNationalid.setForeground(new java.awt.Color(255, 255, 255));
        lblNationalid.setText("COMPLAINANT ID");
        jPanelComplainant.add(lblNationalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 240, 30));
        jPanelComplainant.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 280, 10));

        txtLastName.setBackground(new java.awt.Color(30, 40, 55));
        txtLastName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(255, 255, 255));
        txtLastName.setText("Enter the complainant last name");
        txtLastName.setBorder(null);
        txtLastName.setName("username"); // NOI18N
        txtLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLastNameFocusGained(evt);
            }
        });
        txtLastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLastNameMouseClicked(evt);
            }
        });
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        jPanelComplainant.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 280, 30));

        lblLastname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblLastname.setForeground(new java.awt.Color(255, 255, 255));
        lblLastname.setText("COMPLAINANT LAST NAME");
        jPanelComplainant.add(lblLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 240, 30));

        btnSubmit.setBackground(new java.awt.Color(0, 255, 204));
        btnSubmit.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanelComplainant.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 100, 40));

        lblBack.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblBack.setForeground(new java.awt.Color(255, 255, 255));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/back4.png"))); // NOI18N
        lblBack.setText("BACK");
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        jPanelComplainant.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 40));

        jComboBoxCaseID.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jPanelComplainant.add(jComboBoxCaseID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 110, -1));

        getContentPane().add(jPanelComplainant, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstnameFocusGained
        // TODO add your handling code here:
        txtFirstname.setText("");
    }//GEN-LAST:event_txtFirstnameFocusGained

    private void txtFirstnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFirstnameMouseClicked
        txtFirstname.setText("");
    }//GEN-LAST:event_txtFirstnameMouseClicked

    private void txtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstnameActionPerformed

    private void txtCaseIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCaseIDFocusGained
        // TODO add your handling code here:
        txtCaseID.setText("");
    }//GEN-LAST:event_txtCaseIDFocusGained

    private void txtCaseIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCaseIDMouseClicked
        // TODO add your handling code here:
        txtCaseID.setText("");
    }//GEN-LAST:event_txtCaseIDMouseClicked

    private void txtCaseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaseIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaseIDActionPerformed

    private void txtPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneFocusGained

    private void txtPhoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPhoneMouseClicked
        // TODO add your handling code here:
        txtPhone.setText("");
    }//GEN-LAST:event_txtPhoneMouseClicked

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtNationalidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNationalidFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNationalidFocusGained

    private void txtNationalidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNationalidMouseClicked
        // TODO add your handling code here:
        txtNationalid.setText("");
    }//GEN-LAST:event_txtNationalidMouseClicked

    private void txtNationalidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNationalidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNationalidActionPerformed

    private void txtLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameFocusGained

    private void txtLastNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLastNameMouseClicked
        // TODO add your handling code here:
        txtLastName.setText("");
    }//GEN-LAST:event_txtLastNameMouseClicked

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
         if (txtCaseID.getText().length()==0) {
            JOptionPane.showMessageDialog(null, "Please enter a valid case ID");
        }else if(txtFirstname.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Please enter a valid First Name");
        }else if(txtLastName.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Please enter a valid Last Name");
        }else if(txtNationalid.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Please enter a valid National ID");
        }else if (txtPhone.getText().length()==0) {
            JOptionPane.showMessageDialog(null, "Please enter a valid Phone Number");
        }
        
        String caseID = txtCaseID.getText();
        String firstName = txtFirstname.getText();
        String lastName = txtLastName.getText();
        String nationalID = txtNationalid.getText();
        String phone = txtPhone.getText();
        
        if (!isInt(caseID)) {
            JOptionPane.showMessageDialog(null, "Please Enter a Valid Case ID");
            txtCaseID.setText("");
        } else if (isInt(firstName)) {
            JOptionPane.showMessageDialog(null, "Please Enter A Valid First Name");   
            txtFirstname.setText("");
        }
        else if (isInt(lastName)) {
            JOptionPane.showMessageDialog(null, "Please Enter A Valid Last Name");
            txtLastName.setText("");
        }
        else if (!isInt(nationalID)) {
            JOptionPane.showMessageDialog(null, "Pleaase Enter a Valid Case ID");
            txtNationalid.setText("");
        }
        else if (!isInt(phone)) {
            JOptionPane.showMessageDialog(null, "Pleaase Enter a Valid Case ID");
            txtPhone.setText("");
        }else{
            try {
            
                Class.forName("com.mysql.jdbc.Driver");
                 System.out.println("Connecting to a selected database...");
                //STEP 3: Open a connection
                Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
                System.out.println("Connected database successfully...");

                PreparedStatement statement = conn.prepareStatement("INSERT INTO "
                        + "complainant (case_id,complainant_firstname,complainant_lastname,"
                        + "complainant_phone_number,nationalid) VALUES('"+caseID+"',"
                                + "'"+firstName+"','"+lastName+"',"
                                        + "'"+phone+"','"+nationalID+"')");
                statement.execute();
                System.out.println("Query Excecuted Succesfully");
                JOptionPane.showMessageDialog(null, "Insertion Succesful");
                PoliceHome police = new PoliceHome();
                police.setSize(775,497);
                police.setLocationRelativeTo(null);
                police.pack();
                police.setVisible(true);

                
            }catch (ClassNotFoundException | SQLException a) //catch block
            {
                a.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        // TODO add your handling code here:
        Police police = new Police();
        police.setSize(775,497);
        police.setLocationRelativeTo(null);
        police.pack();
        police.setVisible(true);
       
    }//GEN-LAST:event_lblBackMouseClicked

    private void txtCaseIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCaseIDKeyReleased
        // TODO add your handling code here:
        String ch = txtCaseID.getText();
        jComboBoxCaseID.removeAllItems();
        if (ch.equals("")) {
            jComboBoxCaseID.setVisible(false);
        } else {
            try {
                System.out.println(ch);
                
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
                Statement st = (Statement) conn.createStatement();
                ResultSet rs = st
			.executeQuery("Select case_id from cases where case_id like '"+ ch + "%'");
                while (rs.next()) {
                    String case_id = rs.getString("case_id");
                    if (case_id.equals("")) {
			jComboBoxCaseID.addItem("");
			jComboBoxCaseID.setVisible(false);
                    }else {
			jComboBoxCaseID.addItem(rs.getString("case_id"));
			System.out.println(rs.getString("case_id"));
			jComboBoxCaseID.setVisible(true);
                    }
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(Reporter.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Reporter.class.getName()).log(Level.SEVERE, null, ex);
            }catch (Exception ex) {
            }
            
        }
    }//GEN-LAST:event_txtCaseIDKeyReleased
    
    public static boolean isInt(String s){
        for (int i = 0; i < s.length(); i++) {
            if (!Character.isDigit(s.charAt(i))) {
                return false;
            }
        }
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Complainant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Complainant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Complainant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Complainant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Complainant().setSize(775, 497);
                new Complainant().setLocationRelativeTo(null);
                new Complainant().pack();
                new Complainant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> jComboBoxCaseID;
    private javax.swing.JPanel jPanelComplainant;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblCaseid;
    private javax.swing.JLabel lblCases;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblNationalid;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JTextField txtCaseID;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtNationalid;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
