/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.police;

/**
 *
 * @author Isaack
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHomeIcon = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanelHome = new javax.swing.JPanel();
        lblAdmin = new javax.swing.JLabel();
        lblPolice = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHomeIcon.setBackground(new java.awt.Color(0, 204, 204));
        jPanelHomeIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/home.png"))); // NOI18N
        jPanelHomeIcon.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 140, 150));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setText("MOTTO: Service To Humanity");
        jPanelHomeIcon.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 260, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel10.setText("MADARAKA POLICE STATION");
        jPanelHomeIcon.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 340, 50));

        getContentPane().add(jPanelHomeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 500));

        jPanelHome.setBackground(new java.awt.Color(30, 40, 55));
        jPanelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/admin2.png"))); // NOI18N
        lblAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdminMouseClicked(evt);
            }
        });
        jPanelHome.add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 130, 110));

        lblPolice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/police.png"))); // NOI18N
        lblPolice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPoliceMouseClicked(evt);
            }
        });
        jPanelHome.add(lblPolice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 140));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ADMINISTRATOR");
        jPanelHome.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, 30));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("POLICE");
        jPanelHome.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        getContentPane().add(jPanelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 410, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblPoliceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPoliceMouseClicked
        // TODO add your handling code here:
       Police police = new Police();
       police.setSize(775,497);
       police.setLocationRelativeTo(null);
       police.pack();
       police.setVisible(true);
       
        
    }//GEN-LAST:event_lblPoliceMouseClicked

    private void lblAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminMouseClicked
        // TODO add your handling code here:
        Admin admin = new Admin();
        admin.setSize(775,497);
        admin.setLocationRelativeTo(null);
        admin.pack();
        admin.setVisible(true);
    }//GEN-LAST:event_lblAdminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setSize(775,497);
                new Home().setLocationRelativeTo(null);
                new Home().pack();
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelHomeIcon;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblPolice;
    // End of variables declaration//GEN-END:variables
}
