/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.police;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Wrapper;
import javax.swing.JOptionPane;

/**
 *
 * @author Isaack
 */
public class Police extends javax.swing.JFrame {
            static final String DB_URL = "jdbc:mysql://localhost/police_management_system";
 
	    //  Database credentials
	    static final String USER = "root" ;
	    static final String PASS = "Isaamille2017";
            protected static final String String = null;
             
       
    /**
     * Creates new form Police
     */
    public Police() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblAdmin = new javax.swing.JLabel();
        lblBadgenumber = new javax.swing.JLabel();
        txtBadgenumber = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblPassword = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/police.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 120, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 500));

        jPanel2.setBackground(new java.awt.Color(30, 40, 55));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdmin.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lblAdmin.setText("POLICE");
        jPanel2.add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, 30));

        lblBadgenumber.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblBadgenumber.setForeground(new java.awt.Color(255, 255, 255));
        lblBadgenumber.setText("BADGE NUMBER");
        jPanel2.add(lblBadgenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 150, 30));

        txtBadgenumber.setBackground(new java.awt.Color(30, 40, 55));
        txtBadgenumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBadgenumber.setForeground(new java.awt.Color(255, 255, 255));
        txtBadgenumber.setText("Enter your badge number");
        txtBadgenumber.setBorder(null);
        txtBadgenumber.setName("username"); // NOI18N
        txtBadgenumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBadgenumberFocusGained(evt);
            }
        });
        txtBadgenumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBadgenumberMouseClicked(evt);
            }
        });
        txtBadgenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBadgenumberActionPerformed(evt);
            }
        });
        jPanel2.add(txtBadgenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 280, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 280, 10));

        lblPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("PASSWORD");
        jPanel2.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 100, 30));

        password.setBackground(new java.awt.Color(30, 40, 55));
        password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password.setText("Enter your password");
        password.setBorder(null);
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 280, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 280, -1));

        btnLogin.setBackground(new java.awt.Color(0, 204, 204));
        btnLogin.setText("SIGN IN");
        btnLogin.setBorder(null);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 373, 60, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 410, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBadgenumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBadgenumberFocusGained
        // TODO add your handling code here:
        txtBadgenumber.setText("");
    }//GEN-LAST:event_txtBadgenumberFocusGained

    private void txtBadgenumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBadgenumberMouseClicked
        txtBadgenumber.setText("");
    }//GEN-LAST:event_txtBadgenumberMouseClicked

    private void txtBadgenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBadgenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBadgenumberActionPerformed

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        // TODO add your handling code here:
        password.setText("");
    }//GEN-LAST:event_passwordMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
         Wrapper conn = null;
         if (txtBadgenumber.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please Enter your Badge Number");
        }else if(password.getPassword().length==0){
            JOptionPane.showMessageDialog(null, "Enter a valid password");
        }else{
            String user = txtBadgenumber.getText();   // Collecting the input
            char[] pass = password.getPassword(); // Collecting the input
            String pwd = String.copyValueOf(pass);  // converting from array to string
             if (validate_login(user, pwd)) {
                 JOptionPane.showMessageDialog(null, "Correct Login Credentials");
                    PoliceHome home = new PoliceHome();
                    
                    home.setSize(775,497);
                    home.setLocationRelativeTo(null);
                    home.pack();
                    home.setVisible(true);
             }else{
                 JOptionPane.showMessageDialog(null, "Incorrect Login Credentials"); 
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed
     private boolean validate_login(String username,String password) {
        try{           
       Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
       Connection conn = DriverManager.getConnection(DB_URL,USER,PASS);  
       System.out.println("Connected database successfully...");
       PreparedStatement pst = (PreparedStatement) conn.prepareStatement("Select badge_number,password from police where badge_number=? and password=?");
       pst.setString(1, username); 
       pst.setString(2, password);
       ResultSet rs = pst.executeQuery();                        
       if(rs.next())            
           return true;    
       else
           return false;            
   }
   catch(Exception e){
       e.printStackTrace();
       return false;
   }       
}
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Police.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Police.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Police.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Police.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Police().setVisible(true);
                new Police().setSize(800,600);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblBadgenumber;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField txtBadgenumber;
    // End of variables declaration//GEN-END:variables
}
