/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.police;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static project.police.Reporter.DB_URL;
import static project.police.Reporter.isInt;

/**
 *
 * @author Isaack
 */
public class PoliceOverview extends javax.swing.JFrame {

        static final String DB_URL = "jdbc:mysql://localhost/police_management_system";
 
        //  Database credentials
        static final String USER = "root" ;
        static final String PASS = "Isaamille2017";
    /**
     * Creates new form PoliceOverview
     */
    public PoliceOverview() {
        initComponents();
        Show_Police_In_Table();
    }
     public Connection getConnection(){
        Connection conn;
        try {
            conn = DriverManager.getConnection(DB_URL, USER, PASS); 
            
            return conn;
        } catch (SQLException e) {
            return null;
        }
    }
    
    public ArrayList<PoliceOfficer> getPoliceList(){
        ArrayList<PoliceOfficer> policeList = new ArrayList<>();
        Connection connection = getConnection();
        
        String query = "SELECT * FROM police";
        Statement st;
        ResultSet rs;
        
        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            PoliceOfficer police;
            while (rs.next()) {                
                police = new PoliceOfficer(rs.getInt("police_id"),
                rs.getString("police_firstname"),rs.getString("police_lastname"),
                rs.getInt("police_phone_number"),rs.getString("nationalid"),
                rs.getString("rank"),
                rs.getString("badge_number"),rs.getString("password"));
                policeList.add(police);
            }
        } catch (SQLException e) {
        }
        return policeList;
    }
    
    //DISPLAY DATA IN THE JTABLE
    public void Show_Police_In_Table(){
        ArrayList<PoliceOfficer> list = getPoliceList();
        DefaultTableModel model = (DefaultTableModel) jTable_Display_Police.getModel();
        Object[] row = new Object[8];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getPoliceID();
            row[1] = list.get(i).getFirstName();
            row[2] = list.get(i).getLastName();
            row[3] = list.get(i).getPhoneNumber();
            row[4] = list.get(i).getNationalID();
            row[5] = list.get(i).getRank();
            row[6] = list.get(i).getBadgeNumber();
            row[7] = list.get(i).getPassword();
            
            model.addRow(row);
        }
    }
 
    
    public void excecuteSQLQuery(String query, String message){
        Connection con = getConnection();
        Statement st;
        try {
            st = con.createStatement();
            if ((st.executeUpdate(query) == 1)) {
                //Refresh the Data in the table
                DefaultTableModel model = (DefaultTableModel) jTable_Display_Police.getModel();
                model.setRowCount(0);
                Show_Police_In_Table();
                JOptionPane.showMessageDialog(null, "Data "+message+" Succesfully");
            }else{
               JOptionPane.showMessageDialog(null, "Data Not "+message);
            }
        } catch (Exception e) {
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelComplainant = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txtFirstname = new javax.swing.JTextField();
        lblFirstname = new javax.swing.JLabel();
        lblCases = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtNationalid = new javax.swing.JTextField();
        lblNationalid = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtLastName = new javax.swing.JTextField();
        lblLastname = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_Police = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jSeparator7 = new javax.swing.JSeparator();
        lblNationalid1 = new javax.swing.JLabel();
        txtBadgeNumber = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lblNationalid2 = new javax.swing.JLabel();
        txtRank = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        lblNationalid3 = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        lblFirstname1 = new javax.swing.JLabel();
        txtPoliceID = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblBack = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelComplainant.setBackground(new java.awt.Color(30, 40, 55));
        jPanelComplainant.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelComplainant.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 280, 10));

        txtFirstname.setBackground(new java.awt.Color(30, 40, 55));
        txtFirstname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtFirstname.setForeground(new java.awt.Color(255, 255, 255));
        txtFirstname.setText("Enter the Police Officer first name");
        txtFirstname.setBorder(null);
        txtFirstname.setName("username"); // NOI18N
        txtFirstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFirstnameFocusGained(evt);
            }
        });
        txtFirstname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFirstnameMouseClicked(evt);
            }
        });
        txtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstnameActionPerformed(evt);
            }
        });
        jPanelComplainant.add(txtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 280, 30));

        lblFirstname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblFirstname.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstname.setText("POLICE FIRST NAME");
        jPanelComplainant.add(lblFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 240, 30));

        lblCases.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        lblCases.setForeground(new java.awt.Color(255, 255, 255));
        lblCases.setText("POLICE OFFICER OVERVIEW");
        jPanelComplainant.add(lblCases, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 300, 30));

        lblPhone.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblPhone.setText("POLICE PHONE");
        jPanelComplainant.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 240, 30));

        txtPhone.setBackground(new java.awt.Color(30, 40, 55));
        txtPhone.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(255, 255, 255));
        txtPhone.setText("Enter the phone number");
        txtPhone.setBorder(null);
        txtPhone.setName("username"); // NOI18N
        txtPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPhoneFocusGained(evt);
            }
        });
        txtPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPhoneMouseClicked(evt);
            }
        });
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        jPanelComplainant.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 280, 30));
        jPanelComplainant.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 280, 10));
        jPanelComplainant.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 300, 10));

        txtNationalid.setBackground(new java.awt.Color(30, 40, 55));
        txtNationalid.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNationalid.setForeground(new java.awt.Color(255, 255, 255));
        txtNationalid.setText("Enter the Police Officer national ID");
        txtNationalid.setBorder(null);
        txtNationalid.setName("username"); // NOI18N
        txtNationalid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNationalidFocusGained(evt);
            }
        });
        txtNationalid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNationalidMouseClicked(evt);
            }
        });
        txtNationalid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNationalidActionPerformed(evt);
            }
        });
        jPanelComplainant.add(txtNationalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 280, 30));

        lblNationalid.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNationalid.setForeground(new java.awt.Color(255, 255, 255));
        lblNationalid.setText("NATIONAL ID");
        jPanelComplainant.add(lblNationalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 240, 30));
        jPanelComplainant.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 280, 10));

        txtLastName.setBackground(new java.awt.Color(30, 40, 55));
        txtLastName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(255, 255, 255));
        txtLastName.setText("Enter the Police Officer last name");
        txtLastName.setBorder(null);
        txtLastName.setName("username"); // NOI18N
        txtLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLastNameFocusGained(evt);
            }
        });
        txtLastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLastNameMouseClicked(evt);
            }
        });
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        jPanelComplainant.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 280, 30));

        lblLastname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblLastname.setForeground(new java.awt.Color(255, 255, 255));
        lblLastname.setText("POLICE LAST NAME");
        jPanelComplainant.add(lblLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 240, 30));

        jTable_Display_Police.setBackground(new java.awt.Color(30, 40, 55));
        jTable_Display_Police.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTable_Display_Police.setForeground(new java.awt.Color(255, 255, 255));
        jTable_Display_Police.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Police ID", " First Name", "Last Name", "Phone Number", "National ID", "Rank", "Badge Number", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Display_Police.setRowHeight(25);
        jTable_Display_Police.setSelectionForeground(new java.awt.Color(30, 40, 55));
        jTable_Display_Police.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Display_PoliceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Display_Police);

        jPanelComplainant.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 850, 370));

        btnDelete.setBackground(new java.awt.Color(0, 204, 204));
        btnDelete.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/delete.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.setBorder(null);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanelComplainant.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 520, 150, 60));

        btnUpdate.setBackground(new java.awt.Color(0, 204, 204));
        btnUpdate.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/update.png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.setBorder(null);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanelComplainant.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, 150, 60));

        password.setBackground(new java.awt.Color(30, 40, 55));
        password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password.setText("Enter your password");
        password.setBorder(null);
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        jPanelComplainant.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 280, 30));
        jPanelComplainant.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 280, -1));

        lblNationalid1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNationalid1.setForeground(new java.awt.Color(255, 255, 255));
        lblNationalid1.setText("PASSWORD");
        jPanelComplainant.add(lblNationalid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 240, 30));

        txtBadgeNumber.setBackground(new java.awt.Color(30, 40, 55));
        txtBadgeNumber.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtBadgeNumber.setForeground(new java.awt.Color(255, 255, 255));
        txtBadgeNumber.setText("Enter the Police Officer Badge Number");
        txtBadgeNumber.setBorder(null);
        txtBadgeNumber.setName("username"); // NOI18N
        txtBadgeNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBadgeNumberFocusGained(evt);
            }
        });
        txtBadgeNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBadgeNumberMouseClicked(evt);
            }
        });
        txtBadgeNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBadgeNumberActionPerformed(evt);
            }
        });
        jPanelComplainant.add(txtBadgeNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 280, 30));
        jPanelComplainant.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 300, 10));

        lblNationalid2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNationalid2.setForeground(new java.awt.Color(255, 255, 255));
        lblNationalid2.setText("RANK");
        jPanelComplainant.add(lblNationalid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 240, 30));

        txtRank.setBackground(new java.awt.Color(30, 40, 55));
        txtRank.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtRank.setForeground(new java.awt.Color(255, 255, 255));
        txtRank.setText("Enter the police Officer Rank");
        txtRank.setBorder(null);
        txtRank.setName("username"); // NOI18N
        txtRank.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRankFocusGained(evt);
            }
        });
        txtRank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRankMouseClicked(evt);
            }
        });
        txtRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRankActionPerformed(evt);
            }
        });
        jPanelComplainant.add(txtRank, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 280, 30));
        jPanelComplainant.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 300, 10));

        lblNationalid3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNationalid3.setForeground(new java.awt.Color(255, 255, 255));
        lblNationalid3.setText("BADGE NUMBER");
        jPanelComplainant.add(lblNationalid3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 240, 30));

        btnInsert.setBackground(new java.awt.Color(0, 204, 204));
        btnInsert.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/insert.png"))); // NOI18N
        btnInsert.setText("INSERT");
        btnInsert.setBorder(null);
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanelComplainant.add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, 150, 60));

        lblFirstname1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblFirstname1.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstname1.setText("POLICE ID");
        jPanelComplainant.add(lblFirstname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 240, 30));

        txtPoliceID.setBackground(new java.awt.Color(30, 40, 55));
        txtPoliceID.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPoliceID.setForeground(new java.awt.Color(255, 255, 255));
        txtPoliceID.setText("Enter the Police Officer ID");
        txtPoliceID.setBorder(null);
        txtPoliceID.setName("username"); // NOI18N
        txtPoliceID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPoliceIDFocusGained(evt);
            }
        });
        txtPoliceID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPoliceIDMouseClicked(evt);
            }
        });
        txtPoliceID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPoliceIDActionPerformed(evt);
            }
        });
        jPanelComplainant.add(txtPoliceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 280, 30));
        jPanelComplainant.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 280, 10));

        lblBack.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblBack.setForeground(new java.awt.Color(255, 255, 255));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/back4.png"))); // NOI18N
        lblBack.setText("BACK");
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        jPanelComplainant.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 40));

        lblExit.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/exit2.png"))); // NOI18N
        lblExit.setText("EXIT");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        jPanelComplainant.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, 70, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelComplainant, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelComplainant, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstnameFocusGained
        // TODO add your handling code here:
        txtFirstname.setText("");
    }//GEN-LAST:event_txtFirstnameFocusGained

    private void txtFirstnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFirstnameMouseClicked
        txtFirstname.setText("");
    }//GEN-LAST:event_txtFirstnameMouseClicked

    private void txtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstnameActionPerformed

    private void txtPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusGained
        // TODO add your handling code here:
        txtPhone.setText("");
    }//GEN-LAST:event_txtPhoneFocusGained

    private void txtPhoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPhoneMouseClicked
        // TODO add your handling code here:
        txtPhone.setText("");
    }//GEN-LAST:event_txtPhoneMouseClicked

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtNationalidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNationalidFocusGained
        // TODO add your handling code here:
        txtNationalid.setText("");
    }//GEN-LAST:event_txtNationalidFocusGained

    private void txtNationalidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNationalidMouseClicked
        // TODO add your handling code here:
        txtNationalid.setText("");
    }//GEN-LAST:event_txtNationalidMouseClicked

    private void txtNationalidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNationalidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNationalidActionPerformed

    private void txtLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastNameFocusGained
        // TODO add your handling code here:
        txtLastName.setText("");
    }//GEN-LAST:event_txtLastNameFocusGained

    private void txtLastNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLastNameMouseClicked
        // TODO add your handling code here:
        txtLastName.setText("");
    }//GEN-LAST:event_txtLastNameMouseClicked

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String query = "DELETE FROM police where police_id='"+txtPoliceID.getText()+"'";
        excecuteSQLQuery(query, "Deleted");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        
            String query = "UPDATE police SET police_firstname='"+txtFirstname.getText()+"', "
                    + "police_lastname='"+txtLastName.getText()+"', police_phone_number='"+txtPhone.getText()+"', "
                    + "nationalid='"+txtNationalid.getText()+"', rank='"+txtRank.getText()+"', "
                    + "badge_number='"+txtBadgeNumber.getText()+"', "
                    + "password='"+password.getText()+"' WHERE police_id='"+txtPoliceID.getText()+"'";
            excecuteSQLQuery(query, "Updated");
      
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        // TODO add your handling code here:
        password.setText("");
    }//GEN-LAST:event_passwordMouseClicked

    private void txtBadgeNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBadgeNumberFocusGained
        // TODO add your handling code here:
        txtBadgeNumber.setText("");
    }//GEN-LAST:event_txtBadgeNumberFocusGained

    private void txtBadgeNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBadgeNumberMouseClicked
        // TODO add your handling code here:
        txtBadgeNumber.setText("");
    }//GEN-LAST:event_txtBadgeNumberMouseClicked

    private void txtBadgeNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBadgeNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBadgeNumberActionPerformed

    private void txtRankFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRankFocusGained
        // TODO add your handling code here:
        txtRank.setText("");
    }//GEN-LAST:event_txtRankFocusGained

    private void txtRankMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRankMouseClicked
        // TODO add your handling code here:
         txtRank.setText("");
    }//GEN-LAST:event_txtRankMouseClicked

    private void txtRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRankActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
      
       
    }//GEN-LAST:event_btnInsertActionPerformed

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
        password.setText("");
    }//GEN-LAST:event_passwordFocusGained

    private void jTable_Display_PoliceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_PoliceMouseClicked
        // TODO add your handling code here:
        //Display Selected Row in JTextFields
        int i = jTable_Display_Police.getSelectedRow();
        TableModel model = jTable_Display_Police.getModel();
        txtPoliceID.setText(model.getValueAt(i, 0).toString());
        txtFirstname.setText(model.getValueAt(i, 1).toString());
        txtLastName.setText(model.getValueAt(i, 2).toString());
        txtPhone.setText(model.getValueAt(i, 3).toString());
        txtNationalid.setText(model.getValueAt(i, 4).toString());
        txtRank.setText(model.getValueAt(i, 5).toString());
        txtBadgeNumber.setText(model.getValueAt(i, 6).toString());
        password.setText(model.getValueAt(i, 7).toString());
        
    }//GEN-LAST:event_jTable_Display_PoliceMouseClicked

    private void txtPoliceIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPoliceIDFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPoliceIDFocusGained

    private void txtPoliceIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPoliceIDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPoliceIDMouseClicked

    private void txtPoliceIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPoliceIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPoliceIDActionPerformed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        // TODO add your handling code here:
       AdminHome admin = new AdminHome();
        admin.setSize(1200,650);
        admin.setLocationRelativeTo(null);
        admin.pack();
        admin.setVisible(true);
    }//GEN-LAST:event_lblBackMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PoliceOverview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PoliceOverview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PoliceOverview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PoliceOverview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PoliceOverview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanelComplainant;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable_Display_Police;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblCases;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblFirstname1;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblNationalid;
    private javax.swing.JLabel lblNationalid1;
    private javax.swing.JLabel lblNationalid2;
    private javax.swing.JLabel lblNationalid3;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField txtBadgeNumber;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtNationalid;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPoliceID;
    private javax.swing.JTextField txtRank;
    // End of variables declaration//GEN-END:variables
}
