/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.police;

/**
 *
 * @author Isaack
 */
public class PoliceHome extends javax.swing.JFrame {

    /**
     * Creates new form PoliceHome
     */
    public PoliceHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblComplainant = new javax.swing.JLabel();
        lblCases = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblReporter = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblReporterReport = new javax.swing.JLabel();
        lblCasesReport = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblComplainantReport = new javax.swing.JLabel();
        lblComplainant3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(30, 40, 55));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblComplainant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/person.png"))); // NOI18N
        lblComplainant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblComplainantMouseClicked(evt);
            }
        });
        jPanel1.add(lblComplainant, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 130, 120));

        lblCases.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/complaints.png"))); // NOI18N
        lblCases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCasesMouseClicked(evt);
            }
        });
        jPanel1.add(lblCases, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 130, 120));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("REPORTER");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 130, -1));

        lblReporter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/person.png"))); // NOI18N
        lblReporter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReporterMouseClicked(evt);
            }
        });
        jPanel1.add(lblReporter, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 130, 130));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("COMPLAINANT");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 190, -1));

        lblLogout.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/exit2.png"))); // NOI18N
        lblLogout.setText("LOGOUT");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });
        jPanel1.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CASES");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 90, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("MODULES");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 150, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("REPORTS");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 110, -1));

        lblExit.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/exit2.png"))); // NOI18N
        lblExit.setText("EXIT");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        jPanel1.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 70, 40));

        lblReporterReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/reporter-report.png"))); // NOI18N
        lblReporterReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReporterReportMouseClicked(evt);
            }
        });
        jPanel1.add(lblReporterReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 130, 160));

        lblCasesReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/reporter-report.png"))); // NOI18N
        lblCasesReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCasesReportMouseClicked(evt);
            }
        });
        jPanel1.add(lblCasesReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 140, 150));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("COMPLAINANT REPORT");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 210, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("CASES REPORT");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 130, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("REPORTER'S REPORT");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 190, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 10, 420));

        lblComplainantReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/reporter-report.png"))); // NOI18N
        lblComplainantReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblComplainantReportMouseClicked(evt);
            }
        });
        jPanel1.add(lblComplainantReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 130, 160));

        lblComplainant3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/reporter-report.png"))); // NOI18N
        lblComplainant3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblComplainant3MouseClicked(evt);
            }
        });
        jPanel1.add(lblComplainant3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 130, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCasesMouseClicked
        // TODO add your handling code here:
        Cases cases = new Cases();
        cases.setSize(775,497);
        cases.setLocationRelativeTo(null);
        cases.pack();
        cases.setVisible(true);
        
        
        
    }//GEN-LAST:event_lblCasesMouseClicked

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
        Police police = new Police();
        police.setSize(775,497);
        police.setLocationRelativeTo(null);
        police.pack();
        police.setVisible(true);
        
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblComplainantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComplainantMouseClicked
        // TODO add your handling code here:
        Complainant complainant = new Complainant();
        complainant.setSize(775, 497);
        complainant.setLocationRelativeTo(null);
        complainant.pack();
        complainant.setVisible(true);
    }//GEN-LAST:event_lblComplainantMouseClicked

    private void lblReporterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReporterMouseClicked
        // TODO add your handling code here:
        Reporter reporter = new Reporter();
        reporter.setSize(775, 497);
        reporter.setLocationRelativeTo(null);
        reporter.pack();
        reporter.setVisible(true);
    }//GEN-LAST:event_lblReporterMouseClicked

    private void lblReporterReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReporterReportMouseClicked
        // TODO add your handling code here:
        ReportersReport cr = new ReportersReport();
        cr.setSize(775,497);
        cr.setLocationRelativeTo(null);
        cr.pack();
        cr.setVisible(true);
    }//GEN-LAST:event_lblReporterReportMouseClicked

    private void lblCasesReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCasesReportMouseClicked
        // TODO add your handling code here:
        CasesReport cr = new CasesReport();
        cr.setSize(775,497);
        cr.setLocationRelativeTo(null);
        cr.pack();
        cr.setVisible(true);
        
    }//GEN-LAST:event_lblCasesReportMouseClicked

    private void lblComplainantReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComplainantReportMouseClicked
        // TODO add your handling code here
        ComplainantReport cr = new ComplainantReport();
        cr.setSize(775, 497);
        cr.setLocationRelativeTo(null);
        cr.pack();
        cr.setVisible(true);
    }//GEN-LAST:event_lblComplainantReportMouseClicked

    private void lblComplainant3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComplainant3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblComplainant3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PoliceHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PoliceHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PoliceHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PoliceHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PoliceHome().setSize(775,497);
                new PoliceHome().setLocationRelativeTo(null);
                new PoliceHome().pack();
                new PoliceHome().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCases;
    private javax.swing.JLabel lblCasesReport;
    private javax.swing.JLabel lblComplainant;
    private javax.swing.JLabel lblComplainant3;
    private javax.swing.JLabel lblComplainantReport;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblReporter;
    private javax.swing.JLabel lblReporterReport;
    // End of variables declaration//GEN-END:variables
}
