/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.police;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static project.police.ReportersReport.DB_URL;

/**
 *
 * @author Isaack
 */
public final class ReporterOverview extends javax.swing.JFrame {
    static final String DB_URL = "jdbc:mysql://localhost/police_management_system";
    //  Database credentials
    static final String USER = "root" ;
    static final String PASS = "Isaamille2017";

    /**
     * Creates new form ReporterOverview
     */
    public ReporterOverview() {
        initComponents();
        Show_Reporter_In_Table();
    }
    
    public Connection getConnection(){
        Connection conn;
        try {
            conn = DriverManager.getConnection(DB_URL, USER, PASS); 
            return conn;
        } catch (SQLException e) {
            return null;
        }
    }
     public ArrayList<Reporters> getReporterList(){
        ArrayList<Reporters> reporterList;
        reporterList = new ArrayList<>();
        Connection connection = getConnection();
        
        String query = "SELECT * FROM reporter";
        Statement st;
        ResultSet rs;
        
        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Reporters reporter;
            while (rs.next()) {                
                reporter = new Reporters(rs.getInt("reporter_id"),rs.getInt("case_id"),
                rs.getString("reporter_firstname"),rs.getString("reporter_lastname"),
                rs.getInt("reporter_phone_number"),rs.getInt("nationalid"));
                reporterList.add(reporter);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return reporterList;
    }
    
//    DISPLAY DATA IN THE JTABLE
    public void Show_Reporter_In_Table(){
        ArrayList<Reporters> list = getReporterList();
        DefaultTableModel model = (DefaultTableModel) jTable_Show_Reporters.getModel();
        Object[] row = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getCaseID();
            row[2] = list.get(i).getFirstName();
            row[3] = list.get(i).getLastName();
            row[4] = list.get(i).getPhoneNumber();
            row[5] = list.get(i).getNationalID();
            
            model.addRow(row);
        }
    }
    
    public void excecuteSQLQuery(String query, String message){
        Connection con = getConnection();
        Statement st;
        try {
            st = con.createStatement();
            if ((st.executeUpdate(query) == 1)) {
                //Refresh the Data in the table
                DefaultTableModel model = (DefaultTableModel) jTable_Show_Reporters.getModel();
                model.setRowCount(0);
                Show_Reporter_In_Table();
                JOptionPane.showMessageDialog(null, "Data "+message+" Succesfully");
            }else{
               JOptionPane.showMessageDialog(null, "Data Not "+message);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtCaseID = new javax.swing.JTextField();
        lblNationalid = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblLastname = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblFirstname = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        lblCaseid = new javax.swing.JLabel();
        lblCases = new javax.swing.JLabel();
        txtNationalid = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Show_Reporters = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblCaseid1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lblBack = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(30, 40, 55));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 280, 10));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 280, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 280, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 280, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 280, 10));

        txtCaseID.setBackground(new java.awt.Color(30, 40, 55));
        txtCaseID.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCaseID.setForeground(new java.awt.Color(255, 255, 255));
        txtCaseID.setText("Enter the case ID");
        txtCaseID.setBorder(null);
        txtCaseID.setName("username"); // NOI18N
        txtCaseID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCaseIDFocusGained(evt);
            }
        });
        txtCaseID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCaseIDMouseClicked(evt);
            }
        });
        txtCaseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaseIDActionPerformed(evt);
            }
        });
        txtCaseID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCaseIDKeyReleased(evt);
            }
        });
        jPanel2.add(txtCaseID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 280, 30));

        lblNationalid.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNationalid.setForeground(new java.awt.Color(255, 255, 255));
        lblNationalid.setText("REPORTER NATIONAL ID");
        jPanel2.add(lblNationalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 240, 30));

        lblPhone.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblPhone.setText("REPORTER PHONE");
        jPanel2.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 240, 30));

        lblLastname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblLastname.setForeground(new java.awt.Color(255, 255, 255));
        lblLastname.setText("REPORTER LAST NAME");
        jPanel2.add(lblLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 240, 30));

        txtLastName.setBackground(new java.awt.Color(30, 40, 55));
        txtLastName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(255, 255, 255));
        txtLastName.setText("Enter the reporter's last name");
        txtLastName.setBorder(null);
        txtLastName.setName("username"); // NOI18N
        txtLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLastNameFocusGained(evt);
            }
        });
        txtLastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLastNameMouseClicked(evt);
            }
        });
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 280, 30));

        lblFirstname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblFirstname.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstname.setText("REPORTER FIRST NAME");
        jPanel2.add(lblFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 240, 30));

        txtFirstname.setBackground(new java.awt.Color(30, 40, 55));
        txtFirstname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtFirstname.setForeground(new java.awt.Color(255, 255, 255));
        txtFirstname.setText("Enter the reporter's first name");
        txtFirstname.setBorder(null);
        txtFirstname.setName("username"); // NOI18N
        txtFirstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFirstnameFocusGained(evt);
            }
        });
        txtFirstname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFirstnameMouseClicked(evt);
            }
        });
        txtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstnameActionPerformed(evt);
            }
        });
        jPanel2.add(txtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 280, 30));

        lblCaseid.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCaseid.setForeground(new java.awt.Color(255, 255, 255));
        lblCaseid.setText("CASE ID");
        jPanel2.add(lblCaseid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 110, 30));

        lblCases.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblCases.setForeground(new java.awt.Color(255, 255, 255));
        lblCases.setText("REPORTER OVERVIEW");
        jPanel2.add(lblCases, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 260, 30));

        txtNationalid.setBackground(new java.awt.Color(30, 40, 55));
        txtNationalid.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNationalid.setForeground(new java.awt.Color(255, 255, 255));
        txtNationalid.setText("Enter the reporter's national ID");
        txtNationalid.setBorder(null);
        txtNationalid.setName("username"); // NOI18N
        txtNationalid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNationalidFocusGained(evt);
            }
        });
        txtNationalid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNationalidMouseClicked(evt);
            }
        });
        txtNationalid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNationalidActionPerformed(evt);
            }
        });
        jPanel2.add(txtNationalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 280, 30));

        txtPhone.setBackground(new java.awt.Color(30, 40, 55));
        txtPhone.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(255, 255, 255));
        txtPhone.setText("Enter the reporter Phone");
        txtPhone.setBorder(null);
        txtPhone.setName("username"); // NOI18N
        txtPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPhoneFocusGained(evt);
            }
        });
        txtPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPhoneMouseClicked(evt);
            }
        });
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        jPanel2.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 280, 30));

        jTable_Show_Reporters.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTable_Show_Reporters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Case ID", "First Name", "Last Name", "Phone Number", "National ID"
            }
        ));
        jTable_Show_Reporters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Show_ReportersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Show_Reporters);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 780, 380));

        btnDelete.setBackground(new java.awt.Color(0, 204, 204));
        btnDelete.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/delete.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.setBorder(null);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 150, 60));

        btnUpdate.setBackground(new java.awt.Color(0, 204, 204));
        btnUpdate.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/update.png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.setBorder(null);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 150, 60));

        lblCaseid1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCaseid1.setForeground(new java.awt.Color(255, 255, 255));
        lblCaseid1.setText("ID");
        jPanel2.add(lblCaseid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 110, 30));

        txtID.setBackground(new java.awt.Color(30, 40, 55));
        txtID.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtID.setForeground(new java.awt.Color(255, 255, 255));
        txtID.setText("Enter the case ID");
        txtID.setBorder(null);
        txtID.setName("username"); // NOI18N
        txtID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIDFocusGained(evt);
            }
        });
        txtID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIDMouseClicked(evt);
            }
        });
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDKeyReleased(evt);
            }
        });
        jPanel2.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 280, 30));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 280, 10));

        lblBack.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblBack.setForeground(new java.awt.Color(255, 255, 255));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/back4.png"))); // NOI18N
        lblBack.setText("BACK");
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        jPanel2.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 40));

        lblExit.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/police/images/exit2.png"))); // NOI18N
        lblExit.setText("EXIT");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        jPanel2.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, 70, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 650));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCaseIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCaseIDFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaseIDFocusGained

    private void txtCaseIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCaseIDMouseClicked
        // TODO add your handling code here:
        txtCaseID.setText("");
    }//GEN-LAST:event_txtCaseIDMouseClicked

    private void txtCaseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaseIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaseIDActionPerformed

    private void txtCaseIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCaseIDKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtCaseIDKeyReleased

    private void txtLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameFocusGained

    private void txtLastNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLastNameMouseClicked
        // TODO add your handling code here:
        txtLastName.setText("");
    }//GEN-LAST:event_txtLastNameMouseClicked

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtFirstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstnameFocusGained
        // TODO add your handling code here:
        txtFirstname.setText("");
    }//GEN-LAST:event_txtFirstnameFocusGained

    private void txtFirstnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFirstnameMouseClicked
        txtFirstname.setText(" ");
    }//GEN-LAST:event_txtFirstnameMouseClicked

    private void txtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstnameActionPerformed

    private void txtNationalidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNationalidFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNationalidFocusGained

    private void txtNationalidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNationalidMouseClicked
        // TODO add your handling code here:
        txtNationalid.setText("");
    }//GEN-LAST:event_txtNationalidMouseClicked

    private void txtNationalidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNationalidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNationalidActionPerformed

    private void txtPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneFocusGained

    private void txtPhoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPhoneMouseClicked
        // TODO add your handling code here:
        txtPhone.setText("");
    }//GEN-LAST:event_txtPhoneMouseClicked

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String query = "DELETE FROM reporter where case_id='"+txtCaseID.getText()+"'";
        excecuteSQLQuery(query, "Deleted");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         String query = "UPDATE reporter SET case_id='"+txtCaseID.getText()+"', "
                + "reporter_firstname='"+txtFirstname.getText()+"', "
                + "reporter_lastname='"+txtLastName.getText()+"', "
                + "reporter_phone_number='"+txtPhone.getText()+"', "
                + "nationalid='"+txtNationalid.getText()+"' WHERE case_id='"+txtCaseID.getText()+"'";
            excecuteSQLQuery(query, "Updated");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jTable_Show_ReportersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Show_ReportersMouseClicked
         //Display Selected Row in JTextFields
        int i = jTable_Show_Reporters.getSelectedRow();
        TableModel model = jTable_Show_Reporters.getModel();
        txtCaseID.setText(model.getValueAt(i, 1).toString());
        txtFirstname.setText(model.getValueAt(i, 2).toString());
        txtLastName.setText(model.getValueAt(i, 3).toString());
        txtPhone.setText(model.getValueAt(i, 4).toString());
        txtNationalid.setText(model.getValueAt(i, 5).toString());
              
    }//GEN-LAST:event_jTable_Show_ReportersMouseClicked

    private void txtIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDFocusGained

    private void txtIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDMouseClicked

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDKeyReleased

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        // TODO add your handling code here:
       AdminHome admin = new AdminHome();
        admin.setSize(1200,650);
        admin.setLocationRelativeTo(null);
        admin.pack();
        admin.setVisible(true);
    }//GEN-LAST:event_lblBackMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporterOverview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporterOverview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporterOverview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporterOverview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporterOverview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable_Show_Reporters;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblCaseid;
    private javax.swing.JLabel lblCaseid1;
    private javax.swing.JLabel lblCases;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblNationalid;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JTextField txtCaseID;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtNationalid;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
